export const PronoumColumn =
[
    "Un",
    "Une",
    "Des"
];

export const ClassColumn =
[
    "Mage",
    "Archer",
    "Barbare",
    "Elementaliste",
    "Moine",
    "Sorcier ",
    "Alchimiste ",
    "Ingénieur ",
    "Assassin ",
    "Inventeur",
    "Diplomate ",
    "Cavalier",
    "Paladin",
    "Robot",
    "Bandit ",
    "Druide",
    "Paysan",
    "Soldat",
    "Nécromancien",
    "Chasseur"
];

export const RaceColumn = [
    "Monstre",
    "Fantome",
    "Humain",
    "Mort vivant",
    "Hydre",
    "Squelettique",
    "Dragon",
    "Chat",
    "Chien",
    "Pigeon",
    "Oie",
    "Porc",
    "Grenouille",
    "Tortue ",
    "Geant",
    "Golem",
    "Statue",
    "Lapin",
    "Carotte",
    "Mandragore",
    "Scarabée",
    "Crocodile",
    "Cactus",
    "Oignon",
    "Elephant",
    "Corbeau",
    "Méduse",
    "Serpent",
    "Dinosaure",
    "Poulpe",
    "Radis",
    "Blaireau",
    "Rhinocéros",
    "Ours",
    "Nain",
    "Fantome"
];

export const CaracteristicsColumn = [
    "Au grand cou",
    "Bleu",
    "Violet",
    "Orange ",
    "Rouge",
    "Jaune",
    "Rose",
    "Vert",
    "A la face de cul",
    "De feu",
    "De glace",
    "Des arcanes",
    "Feignant",
    "Sylvain ",
    "Vénère ",
    "De la nuit",
    "Des mers",
    "Des ténèbres ",
    "Multi-faces",
    "Avec un masque",
    "Tentaculaire",
    "Avec une très grosse tête ",
    "Aux grandes jambes",
    "Possédé",
    "De lumière ",
    "Effrayant",
    "Gélatineux ",
    "Plein de vers",
    "Pourri ",
    "Plein d'yeux",
    "Dans un coffre",
    "Ailé",
    "Cyclope",
    "Recouvert de plantes",
    "Végétal",
    "Avec un cache oeil",
    "Plein de cicatrices",
    "Avec des bras à ressorts",
    "Doré",
    "Pirate ",
    "Mignon",
    "En lévitation",
    "Sans jambes",
    "Controlé par un petit",
    "Le cerveau à l'air",
    "Avec une crotte sur la tête",
    "Royal",
    "Sous marin",
    "Obèse",
    "Maigre",
    "Mystique",
    "Avec des serpents sur la tête",
    "Avec les yeux qui brillent",
    "Qui n'est qu'une ombre",
    "Transparent",
    "Avec de gros poings",
    "Spatial",
    "Transpercé par des épées",
    "Criblé de flèches",
    "De lave",
    "Mécanique",
    "Gluant",
    "Qui maitrise l'eau",
    "En bois",
    "En pierre",
    "En boue",
    "Avec plusieurs bras",
    "Pleins d'étoiles",
    "Avec un masque de Daruma",
    "Sur un cheval",
    "Sur un âne",
    "Triste",
    "Qui se trasnforme",
    "Magique",
    "Recouvert de champignons",
    "Avec les yeux vides",
    "Avec un oeil sur le frou",
    "Ebouriffé",
    "Minuscule",
    "Poilu",
    "Avec des yeux dans les mains",
    "Balafré ",
    "Avec des ailes d'insecte",
    "Coupé en morceaux",
    "Avec le torse en lévitation",
    "Enflammé",
    "Avec un grand sourire",
    "Sale",
    "En cristal",
    "En fumée"
];

export const SpecialItemColumn = [
    "Un Lance grenades ",
    "Un Casque crâne ",
    "Une Épée de lumière ",
    "Des Bombes ",
    "Une Épée ",
    "Une Épée géante ",
    "Une Baguette magique ",
    "Une hache ",
    "Une croix",
    "Une tour à canon ",
    "Un chariot",
    "Des fioles",
    "Des runes",
    "Une ancre",
    "Un crochet",
    "Une tortue de combat ",
    "Une carabine ",
    "Un cul de cochon ",
    "De multiples dagues",
    "Une arbalète ",
    "Une épée d'os",
    "Un costume mascotte",
    "Un casque a grandes cornes",
    "Une poêle ",
    "Un masque de dragon",
    "Un bouclier rond",
    "Un gros bouclier ",
    "Une brouette",
    "Un tank",
    "Une très longue cape",
    "Des grimoires",
    "Une énorme bombe",
    "Une rame",
    "Un jambon",
    "Un pigeon accroché à une corde",
    "Des pots de fleurs",
    "Une moto",
    "Un balai",
    "Un overboard",
    "Un canon",
    "Des mines",
    "Un pendule",
    "Une pyramide",
    "Une lance",
    "Un baton",
    "Deux insectes de combats",
    "Le septre des crottes",
    "Un septre royal",
    "Une couronne",
    "Une fourche",
    "Des bûches",
    "Un casque coquillage",
    "Des gâteaux",
    "Une mouffle de cuisine",
    "Un masque d'Oni",
    "Un seau",
    "Un casque à visage métalique",
    "Une épuisette",
    "Une boule magique",
    "Une clé",
    "Une boussole",
    "Un spectre",
    "Une citrouille d'halloween",
    "Une tête de monstre",
    "Un drapeau",
    "Un sabre",
    "Un trésor",
    "Un chaudron",
    "Un rateau",
    "Un masque en papier maché",
    "Des gants magique",
    "Une foreuse",
    "Une épée vivante",
    "Un bol de nouilles",
    "Une masse",
    "Une boule de piques",
    "Un steak",
    "Un poulet",
    "Un radis géant",
    "Un fleuret",
    "Une pince",
    "Une cacahuète",
    "Une crotte",
    "Un poulpe",
    "Un casque tourelle canon",
    "Une cloche",
    "Une tronçonneuse",
    "Une double hache",
    "Des pointes sur les mains",
    "Une épée de feu",
    "Un baton de foudre",
    "Un feu de camp",
    "Une cagette de fruits",
    "Un champignon magique",
    "Un petit chapeau rigolo",
    "Un cadeau",
    "Une batte",
    "Une armure renforcée",
    "Une fourchette",
    "Une lanterne",
    "Un tambourin",
    "Un tonneau",
    "Une canne a pêche",
    "Une pelle",
    "Un livre",
    "Un chapeau canotier",
    "Un noeud",
    "Une plante",
    "Une corde",
    "Une poupée",
    "Un jeu de tarot",
    "Une table de ouija",
    "Des chaines",
    "Des gants de boxe",
    "Un épée à dents de scie",
    "Des turbo-poings",
    "Des blocs de pierre",
    "Un énorme rocher",
    "Une théière ",
    "Un feu de camps",
    ];

export const WithColumn = [
    "avec",
    " avec ",
    "avec ",
];